### ISSUE TITLE
In Edit Food Tags, when user queries a tag, it immediately adds it to the database

### ISSUE THREAD

**Issue by luwesaram** [Arc-Data/itinerary-recommender-frontend#52]
![image](https://github.com/Arc-Data/itinerary-recommender-frontend/assets/110721449/dc913465-7fb5-4ef9-9b74-a98e3c6fcbad)

Potential similar issue when activity is implemented

**Comment by Arc-Data** [comment]
non-issue for now, just implement deletion of tags in the future
