### ISSUE TITLE
Can't create spot on admin, and hindi nakakapag add ng opening and closing time

### ISSUE THREAD

**Issue by Emmanuel0725** [Arc-Data/itinerary-recommender-frontend#53]
![image](https://github.com/Arc-Data/itinerary-recommender-frontend/assets/110836090/0fc87ffd-b7a6-4664-a1a6-a8be51874306)
![image](https://github.com/Arc-Data/itinerary-recommender-frontend/assets/110836090/cc521450-bff7-4061-b181-b2b0e4cc3d8f)

**Comment by Arc-Data** [comment]
Unauthorized, refresh lang katapat niyan e
